
SET(LIBS_NAMES hdf5_hl hdf5)

IF( ${PROJECT_NAME}_ENABLE_VERAIn )
  APPEND_SET(LIBS_NAMES hdf5_fortran)
ENDIF()

TRIBITS_TPL_FIND_INCLUDE_DIRS_AND_LIBRARIES( HDF5
  REQUIRED_HEADERS hdf5.h
  REQUIRED_LIBS_NAMES ${LIBS_NAMES} z
  )
